package top.fifthlight.asmnet

data class OpCode(
    val code: Code,
    val prefixes: ShortArray? = null,
) {
    @JvmInline
    value class Code(val value: Short) {
        companion object {
            val nop = Code(0x00)
            val `break` = Code(0x01)
            val ldarg0 = Code(0x02)
            val ldarg1 = Code(0x03)
            val ldarg2 = Code(0x04)
            val ldarg3 = Code(0x05)
            val ldloc0 = Code(0x06)
            val ldloc1 = Code(0x07)
            val ldloc2 = Code(0x08)
            val ldloc3 = Code(0x09)
            val stloc0 = Code(0x0A)
            val stloc1 = Code(0x0B)
            val stloc2 = Code(0x0C)
            val stloc3 = Code(0x0D)
            val ldargS = Code(0x0E)
            val ldargaS = Code(0x0F)
            val stargS = Code(0x10)
            val ldlocS = Code(0x11)
            val ldlocaS = Code(0x12)
            val stlocS = Code(0x13)
            val ldnull = Code(0x14)
            val ldcI4M1 = Code(0x15)
            val ldcI40 = Code(0x16)
            val ldcI41 = Code(0x17)
            val ldcI42 = Code(0x18)
            val ldcI43 = Code(0x19)
            val ldcI44 = Code(0x1A)
            val ldcI45 = Code(0x1B)
            val ldcI46 = Code(0x1C)
            val ldcI47 = Code(0x1D)
            val ldcI48 = Code(0x1E)
            val ldcI4S = Code(0x1F)
            val ldcI4 = Code(0x20)
            val ldcI8 = Code(0x21)
            val ldcR4 = Code(0x22)
            val ldcR8 = Code(0x23)
            val dup = Code(0x25)
            val pop = Code(0x26)
            val jmp = Code(0x27)
            val call = Code(0x28)
            val calli = Code(0x29)
            val ret = Code(0x2A)
            val brS = Code(0x2B)
            val brfalseS = Code(0x2C)
            val brtrueS = Code(0x2D)
            val beqS = Code(0x2E)
            val bgeS = Code(0x2F)
            val bgtS = Code(0x30)
            val bleS = Code(0x31)
            val bltS = Code(0x32)
            val bneUnS = Code(0x33)
            val bgeUnS = Code(0x34)
            val bgtUnS = Code(0x35)
            val bleUnS = Code(0x36)
            val bltUnS = Code(0x37)
            val br = Code(0x38)
            val brfalse = Code(0x39)
            val brtrue = Code(0x3A)
            val beq = Code(0x3B)
            val bge = Code(0x3C)
            val bgt = Code(0x3D)
            val ble = Code(0x3E)
            val blt = Code(0x3F)
            val bneUn = Code(0x40)
            val bgeUn = Code(0x41)
            val bgtUn = Code(0x42)
            val bleUn = Code(0x43)
            val bltUn = Code(0x44)
            val switch = Code(0x45)
            val ldindI1 = Code(0x46)
            val ldindU1 = Code(0x47)
            val ldindI2 = Code(0x48)
            val ldindU2 = Code(0x49)
            val ldindI4 = Code(0x4A)
            val ldindU4 = Code(0x4B)
            val ldindI8 = Code(0x4C)
            val ldindI = Code(0x4D)
            val ldindR4 = Code(0x4E)
            val ldindR8 = Code(0x4F)
            val ldindRef = Code(0x50)
            val stindRef = Code(0x51)
            val stindI1 = Code(0x52)
            val stindI2 = Code(0x53)
            val stindI4 = Code(0x54)
            val stindI8 = Code(0x55)
            val stindR4 = Code(0x56)
            val stindR8 = Code(0x57)
            val add = Code(0x58)
            val sub = Code(0x59)
            val mul = Code(0x5A)
            val div = Code(0x5B)
            val divUn = Code(0x5C)
            val rem = Code(0x5D)
            val remUn = Code(0x5E)
            val and = Code(0x5F)
            val or = Code(0x60)
            val xor = Code(0x61)
            val shl = Code(0x62)
            val shr = Code(0x63)
            val shrUn = Code(0x64)
            val neg = Code(0x65)
            val not = Code(0x66)
            val convI1 = Code(0x67)
            val convI2 = Code(0x68)
            val convI4 = Code(0x69)
            val convI8 = Code(0x6A)
            val convR4 = Code(0x6B)
            val convR8 = Code(0x6C)
            val convU4 = Code(0x6D)
            val convU8 = Code(0x6E)
            val callvirt = Code(0x6F)
            val cpobj = Code(0x70)
            val ldobj = Code(0x71)
            val ldstr = Code(0x72)
            val newobj = Code(0x73)
            val castclass = Code(0x74)
            val isinst = Code(0x75)
            val convRUn = Code(0x76)
            val unbox = Code(0x79)
            val `throw` = Code(0x7A)
            val ldfld = Code(0x7B)
            val ldflda = Code(0x7C)
            val stfld = Code(0x7D)
            val ldsfld = Code(0x7E)
            val ldsflda = Code(0x7F)
            val stsfld = Code(0x80)
            val stobj = Code(0x81)
            val convOvfI1Un = Code(0x82)
            val convOvfI2Un = Code(0x83)
            val convOvfI4Un = Code(0x84)
            val convOvfI8Un = Code(0x85)
            val convOvfU1Un = Code(0x86)
            val convOvfU2Un = Code(0x87)
            val convOvfU4Un = Code(0x88)
            val convOvfU8Un = Code(0x89)
            val convOvfIUn = Code(0x8A)
            val convOvfUUn = Code(0x8B)
            val box = Code(0x8C)
            val newarr = Code(0x8D)
            val ldlen = Code(0x8E)
            val ldelema = Code(0x8F)
            val ldelemI1 = Code(0x90)
            val ldelemU1 = Code(0x91)
            val ldelemI2 = Code(0x92)
            val ldelemU2 = Code(0x93)
            val ldelemI4 = Code(0x94)
            val ldelemU4 = Code(0x95)
            val ldelemI8 = Code(0x96)
            val ldelemI = Code(0x97)
            val ldelemR4 = Code(0x98)
            val ldelemR8 = Code(0x99)
            val ldelemRef = Code(0x9A)
            val stelemI = Code(0x9B)
            val stelemI1 = Code(0x9C)
            val stelemI2 = Code(0x9D)
            val stelemI4 = Code(0x9E)
            val stelemI8 = Code(0x9F)
            val stelemR4 = Code(0xA0)
            val stelemR8 = Code(0xA1)
            val stelemRef = Code(0xA2)
            val ldelem = Code(0xA3)
            val stelem = Code(0xA4)
            val unboxAny = Code(0xA5)
            val convOvfI1 = Code(0xB3)
            val convOvfU1 = Code(0xB4)
            val convOvfI2 = Code(0xB5)
            val convOvfU2 = Code(0xB6)
            val convOvfI4 = Code(0xB7)
            val convOvfU4 = Code(0xB8)
            val convOvfI8 = Code(0xB9)
            val convOvfU8 = Code(0xBA)
            val refanyval = Code(0xC2)
            val ckfinite = Code(0xC3)
            val mkrefany = Code(0xC6)
            val ldtoken = Code(0xD0)
            val convU2 = Code(0xD1)
            val convU1 = Code(0xD2)
            val convI = Code(0xD3)
            val convOvfI = Code(0xD4)
            val convOvfU = Code(0xD5)
            val addOvf = Code(0xD6)
            val addOvfUn = Code(0xD7)
            val mulOvf = Code(0xD8)
            val mulOvfUn = Code(0xD9)
            val subOvf = Code(0xDA)
            val subOvfUn = Code(0xDB)
            val endfinally = Code(0xDC)
            val leave = Code(0xDD)
            val leaveS = Code(0xDE)
            val stindI = Code(0xDF)
            val convU = Code(0xE0)

            val arglist = Code(0xFE00.toShort())
            val ceq = Code(0xFE01.toShort())
            val cgt = Code(0xFE02.toShort())
            val cgtUn = Code(0xFE03.toShort())
            val clt = Code(0xFE04.toShort())
            val cltUn = Code(0xFE05.toShort())
            val ldftn = Code(0xFE06.toShort())
            val ldvirtftn = Code(0xFE07.toShort())
            val ldarg = Code(0xFE09.toShort())
            val ldarga = Code(0xFE0A.toShort())
            val starg = Code(0xFE0B.toShort())
            val ldloc = Code(0xFE0C.toShort())
            val ldloca = Code(0xFE0D.toShort())
            val stloc = Code(0xFE0E.toShort())
            val localloc = Code(0xFE0F.toShort())
            val endfilter = Code(0xFE11.toShort())
            val initobj = Code(0xFE15.toShort())
            val cpblk = Code(0xFE17.toShort())
            val initblk = Code(0xFE18.toShort())
            val rethrow = Code(0xFE1A.toShort())
            val sizeof = Code(0xFE1C.toShort())
            val refanytype = Code(0xFE1D.toShort())

            val brnull = brfalse
            val brnullS = brfalseS
            val brzero = brfalse
            val brzeroS = brfalseS
            val brinst = brtrue
            val brinstS = brtrueS
            val ldindU8 = ldindI8
            val ldelemU8 = ldelemI8
            val ldcI4M1x = ldcI4M1
            val endfault = endfinally
        }
    }

    @JvmInline
    value class Prefix(val value: Short) {
        companion object {
            const val unaligned: Short = 0xFE12.toShort()
            const val volatile: Short = 0xFE13.toShort()
            const val tail: Short = 0xFE14.toShort()
            const val constrained: Short = 0xFE16.toShort()
            const val no: Short = 0xFE19.toShort()
            const val readonly: Short = 0xFE1E.toShort()
        }
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as OpCode

        if (code != other.code) return false
        if (!prefixes.contentEquals(other.prefixes)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = code.hashCode()
        result = 31 * result + (prefixes?.contentHashCode() ?: 0)
        return result
    }
}

fun OpCode(code: OpCode.Code) = OpCode(code, null)
fun OpCode(code: OpCode.Code, vararg prefixes: Short) = OpCode(code, prefixes)
